export const genericEventProcess = `IMPORTANT: Do NOT use any scrollable containers (no overflow-y-auto, or similar CSS). The event list should expand to show all events without internal scrolling. Let the content grow naturally in height.
"Generate a static HTML UI for an event portal, specifically tailored for different type of events (for either one or list of event). The design should be modern, dark-themed, responsive, and centered, with a maximum width of w-full and h-full. Use 'Neue Haas Grotesk Display Pro' font, Font Awesome for icons, and Tailwind CSS for styling.
The UI should include:
    An optional main headerand a descriptive subtitle.
    An optional prominent 'Featured Event' card. This card should have a background image (use an Unsplash image relevant to the event, with a fallback if the URL fails), a clear title, a brief description, event date and time details, a call-to-action button, and a relevant icon overlaid. Ensure text readability against the background image with a dark overlay.
    Optional categorized sections for event listings, such as 'Today's Events,' 'Tomorrow's Events,' and 'Next Week's Events.' Each section should have its own header indicating the category and date.
    Within these event sections, include multiple individual event cards. Each card should use a bg-white/10 background for a consistent, translucent look. Each card should contain a title, a brief description, key details (like time and location), a call-to-action button, and a subtle background icon. Use distinct text colors for titles and icons (e.g., green, blue, orange, purple, red) to visually categorize event types, and ensure the buttons match these colors.
    An optional single 'Specific Event Detail' section that can be uncommented to display a detailed view of one event, typically replacing the other event lists when active. This section should include comprehensive event information like date, venue, speakers, and price.
Ensure all interactive elements (cards, buttons) have rounded corners, subtle shadows, and hover effects. The overall aesthetic should be clean and intuitive, designed for easy navigation of event information. All sections should be structured so they can be easily made optional by commenting out or deleting their respective HTML blocks."`;
